# -*- coding: utf-8 -*-
"""2702371136_Raka Maulana Akbar_Assignment sesi 1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1SseSV3d7ZUECedoMSKzjwf0hKZlwZ5PW
"""

import time
print(time.ctime())

print("halo")

x = 1
y = 2
print(y)
print(x)

x = 1
y = x + 1
x = 2
y

import numpy as np

x = np.array([1, 4, 3])
x

y = np.array([[1, 4, 3], [9, 2, 7]])
y

def my_adder(a, b, c):


    # this is the summation
    out = a + b + c

    return out

my_adder(1,2,3)

def my_thermo_stat(temp, desired_temp):
    if temp < desired_temp - 5:
      status = 'heat'
    elif temp > desired_temp + 5:
      status = 'AC'
    else:
      status = 'OFF'
    return status

status = my_thermo_stat(65,75)
print(status)

status = my_thermo_stat(75,65)
print(status)

status = my_thermo_stat(65,63)
print(status)